# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spisanU.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MWspis(object):
    def setupUi(self, MWspis):
        MWspis.setObjectName("MWspis")
        MWspis.resize(480, 260)
        MWspis.setMinimumSize(QtCore.QSize(480, 260))
        MWspis.setMaximumSize(QtCore.QSize(480, 260))
        self.centralwidget = QtWidgets.QWidget(MWspis)
        self.centralwidget.setObjectName("centralwidget")
        self.pBexit = QtWidgets.QPushButton(self.centralwidget)
        self.pBexit.setGeometry(QtCore.QRect(350, 200, 88, 34))
        self.pBexit.setObjectName("pBexit")
        self.pB = QtWidgets.QPushButton(self.centralwidget)
        self.pB.setGeometry(QtCore.QRect(260, 100, 88, 34))
        self.pB.setObjectName("pB")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 100, 91, 32))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 331, 31))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 100, 87, 32))
        self.comboBox.setStyleSheet("")
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MWspis.setCentralWidget(self.centralwidget)

        self.retranslateUi(MWspis)
        self.pBexit.clicked.connect(MWspis.close)
        self.pB.clicked.connect(MWspis.sSpis)
        QtCore.QMetaObject.connectSlotsByName(MWspis)
        MWspis.setTabOrder(self.comboBox, self.lineEdit)
        MWspis.setTabOrder(self.lineEdit, self.pB)
        MWspis.setTabOrder(self.pB, self.pBexit)

    def retranslateUi(self, MWspis):
        _translate = QtCore.QCoreApplication.translate
        MWspis.setWindowTitle(_translate("MWspis", "Списание приборов"))
        self.pBexit.setText(_translate("MWspis", "Закрыть"))
        self.pB.setText(_translate("MWspis", "Списать"))
        self.comboBox.setItemText(0, _translate("MWspis", "ДВЕ"))
        self.comboBox.setItemText(1, _translate("MWspis", "БС"))
